import { v4 as uuidv4 } from "uuid";
export const produtosAmazon = [
  {
    id: uuidv4(),
    urlImg: "https://m.media-amazon.com/images/I/71kvvuuKK3L._AC_SL1500_.jpg",
    nome: "Filtro de Linha Power Line de 6 tomadas em Gabinete Plástico",
    descricao:
      "Filtro de Linha Power Line de 6 tomadas em Gabinete Plástico",
    alt: "Filtro de Linha Power Line de 6 tomadas em Gabinete Plástico",
    linkDeCompra: "https://amzn.to/4buhso6",
    categoria: "Eletrônico",
  },
  {
    id: uuidv4(),
    urlImg: "https://m.media-amazon.com/images/I/61i2HM5i97L._AC_SL1500_.jpg",
    nome: "Chocolate Sonho de Valsa Pacote 1Kg",
    descricao:
      "Chocolate Sonho de Valsa Pacote 1Kg",
    alt: "Chocolate Sonho de Valsa Pacote 1Kg",
    linkDeCompra: "https://amzn.to/3VXSsQy",
    categoria: "Alimento",
  },
  {
    id: uuidv4(),
    urlImg: "https://m.media-amazon.com/images/I/71hFk5aKMYL._AC_SL1500_.jpg",
    nome: "Bis Original Ao Leite - Kit com 3 unidades de 100,8g",
    descricao:
      "Bis Original Ao Leite - Kit com 3 unidades de 100,8g",
    alt: "Bis Original Ao Leite - Kit com 3 unidades de 100,8g",
    linkDeCompra: "https://amzn.to/3XQklMP",
    categoria: "Alimento",
  },
  {
    id: uuidv4(),
    urlImg: "https://m.media-amazon.com/images/I/51CL2s7YMEL._AC_SL1074_.jpg",
    nome: "Whisky Johnnie Walker Black Label 12 Anos 1L",
    descricao:
      "Whisky Johnnie Walker Black Label 12 Anos 1L",
    alt: "Whisky Johnnie Walker Black Label 12 Anos 1L",
    linkDeCompra: "https://amzn.to/4bxjwMb",
    categoria: "Alimento",
  },
  {
    id: uuidv4(),
    urlImg: "https://m.media-amazon.com/images/I/61OBwSlK+LL._AC_SL1500_.jpg",
    nome: "ELSÉVE Óleo Capilar L'Oréal Paris Elseve Óleo Extraordinário 100Ml -",
    descricao:
      "ELSÉVE Óleo Capilar L'Oréal Paris Elseve Óleo Extraordinário 100Ml -",
    alt: "ELSÉVE Óleo Capilar L'Oréal Paris Elseve Óleo Extraordinário 100Ml -",
    linkDeCompra: "https://amzn.to/4cGGMbz",
    categoria: "Beleza",
  },
  {
    id: uuidv4(),
    urlImg: "https://m.media-amazon.com/images/I/61JSetSXeXL._AC_SL1500_.jpg",
    nome: "Clear Shampoo Men Anticaspa Ice Cool Menthol 400Ml",
    descricao:
      "Clear Shampoo Men Anticaspa Ice Cool Menthol 400Ml",
    alt: "Clear Shampoo Men Anticaspa Ice Cool Menthol 400Ml",
    linkDeCompra: "https://amzn.to/3zkbpFk",
    categoria: "Beleza",
  },
  {
    id: uuidv4(),
    urlImg: "https://m.media-amazon.com/images/I/71aVPs4Sv9L._SL1500_.jpg",
    nome: "Fora de série - Outliers: Descubra por que algumas pessoas têm sucesso e outras não",
    descricao:
      "Fora de série - Outliers: Descubra por que algumas pessoas têm sucesso e outras não",
    alt: "Fora de série - Outliers: Descubra por que algumas pessoas têm sucesso e outras não",
    linkDeCompra: "https://amzn.to/45FnnW7",
    categoria: "Livro",
  },
  {
    id: uuidv4(),
    urlImg: "https://m.media-amazon.com/images/I/619T0W3tfuL._SL1360_.jpg",
    nome: "#umdiasemreclamar: Descubra por que a gratidão pode mudar a sua vida",
    descricao:
      "#umdiasemreclamar: Descubra por que a gratidão pode mudar a sua vida",
    alt: "#umdiasemreclamar: Descubra por que a gratidão pode mudar a sua vida",
    linkDeCompra: "https://amzn.to/4cCkEyW",
    categoria: "Livro",
  },
  {
    id: uuidv4(),
    urlImg: "https://m.media-amazon.com/images/I/61PMSbZ2RIL._AC_SL1000_.jpg",
    nome: "Fire TV Stick Lite",
    descricao:
      "Streaming em Full HD com Alexa | Com Controle Remoto Lite por Voz com Alexa (sem controles de TV)",
    alt: "Fire TV Stick Lite",
    linkDeCompra: "https://amzn.to/4dWofcI",
    categoria: "Eletrônico",
  },
  {
    id: uuidv4(),
    urlImg: "https://m.media-amazon.com/images/I/61+J5+SRkuL._AC_SL1000_.jpg",
    nome: "Fire TV Stick",
    descricao:
      "Streaming em Full HD com Alexa | Com Controle Remoto por Voz com Alexa (inclui comandos de TV)",
    alt: "Fire TV Stick",
    linkDeCompra: "https://amzn.to/3KdT2E6",
    categoria: "Eletrônico",
  },
  {
    id: uuidv4(),
    urlImg: "https://m.media-amazon.com/images/I/715s6W8vqJL._AC_SL1500_.jpg",
    nome: "Fire TV Stick 4K",
    descricao:
      "Streaming com Dolby Vision/Atmos e suporte a wi-fi 6 | Com Alexa e comandos de TV",
    alt: "Fire TV Stick 4k",
    linkDeCompra: "https://amzn.to/4dXLlzu",
    categoria: "Eletrônico",
  },
  {
    id: uuidv4(),
    urlImg: "https://m.media-amazon.com/images/I/617-HLllfZL._AC_SL1000_.jpg",
    nome: "Echo Dot 5ª geração",
    descricao: "O Echo Dot com o melhor som já lançado | Cor Preta",
    alt: "Echo Dot 5ª geração",
    linkDeCompra: "https://amzn.to/4bJ54Bc",
    categoria: "Eletrônico",
  },
  {
    id: uuidv4(),
    urlImg: "https://m.media-amazon.com/images/I/61dLgPIgKML._AC_SL1500_.jpg",
    nome: "Lâmpada Inteligente Smart Color 10W Elgin RGB Wifi Compatível com Alexa e Google Home",
    descricao:
      "Lâmpada Inteligente Smart Color 10W Elgin RGB Wifi Compatível com Alexa e Google Home",
    alt: "Lâmpada Inteligente Smart Color 10W Elgin RGB Wifi Compatível com Alexa e Google Home",
    linkDeCompra: "https://amzn.to/3xttBvy",
    categoria: "Eletrônico",
  },
  {
    id: uuidv4(),
    urlImg: "https://m.media-amazon.com/images/I/61IfUXVbkmL._AC_SL1007_.jpg",
    nome: "Mouse Sem Fio Lenovo 300 Compact 1000dpi Preto",
    descricao:
      "Mouse Sem Fio Lenovo 300 Compact 1000dpi Preto",
    alt: "Mouse Sem Fio Lenovo 300 Compact 1000dpi Preto",
    linkDeCompra: "https://amzn.to/4bfstcR",
    categoria: "Eletrônico",
  },
  {
    id: uuidv4(),
    urlImg: "https://m.media-amazon.com/images/I/61WrR7z-pGL._AC_SL1280_.jpg",
    nome: "Mouse Dell WM126",
    descricao:
      "Mouse Dell WM126",
    alt: "Mouse Dell WM126",
    linkDeCompra: "https://amzn.to/3XAVagZ",
    categoria: "Eletrônico",
  },
  {
    id: uuidv4(),
    urlImg: "https://m.media-amazon.com/images/I/61GwdAH1QZL._AC_SL1500_.jpg",
    nome: "Mouse sem fio Logitech M170 com Design Ambidestro Compacto, Conexão USB e Pilha Inclusa - Preto",
    descricao:
      "Mouse sem fio Logitech M170 com Design Ambidestro Compacto, Conexão USB e Pilha Inclusa - Preto",
    alt: "Mouse sem fio Logitech M170 com Design Ambidestro Compacto, Conexão USB e Pilha Inclusa - Preto",
    linkDeCompra: "https://amzn.to/4ew7iGf",
    categoria: "Eletrônico",
  },
  {
    id: uuidv4(),
    urlImg: "https://m.media-amazon.com/images/I/611J91ovSlL._AC_SL1500_.jpg",
    nome: "Mi Band 8 Active versão global (Preto)",
    descricao:
      "Xiaomi Mi Band 8 Active versão global (Preto)",
    alt: "Xiaomi Mi Band 8 Active versão global (Preto)",
    linkDeCompra: "https://amzn.to/4ezVEdy",
    categoria: "Eletrônico",
  },
  {
    id: uuidv4(),
    urlImg: "https://m.media-amazon.com/images/I/31d2fUdrBaL._AC_SL1080_.jpg",
    nome: "JBL, Fone de Ouvido in Ear, C50HI - Preto",
    descricao: "JBL, Fone de Ouvido in Ear, C50HI - Preto",
    alt: "JBL, Fone de Ouvido in Ear, C50HI - Preto",
    linkDeCompra: "https://amzn.to/45EcrrU",
    categoria: "Eletrônico",
  },
  {
    id: uuidv4(),
    urlImg: "https://m.media-amazon.com/images/I/91iWZmXLOAL._AC_SL1500_.jpg",
    nome: "Headphone Philips bluetooth on-ear",
    descricao: "Headphone Philips bluetooth on-ear",
    alt: "Headphone Philips bluetooth on-ear",
    linkDeCompra: "https://amzn.to/4exUYoU",
    categoria: "Eletrônico",
  },
  {
    id: uuidv4(),
    urlImg: "https://m.media-amazon.com/images/I/41k-cvl8n-L._AC_.jpg",
    nome: "Película TPU Gel para Xiaomi Mi Band 8 Active, Mi Smart Band 8 active (Exclusivo) c/ 2 un",
    descricao: "Película TPU Gel para Xiaomi Mi Band 8 Active, Mi Smart Band 8 active (Exclusivo) c/ 2 un",
    alt: "Película TPU Gel para Xiaomi Mi Band 8 Active, Mi Smart Band 8 active (Exclusivo) c/ 2 un",
    linkDeCompra: "https://amzn.to/4eBu0g0",
    categoria: "Pelicula",
  },
  {
    id: uuidv4(),
    urlImg: "https://m.media-amazon.com/images/I/71W42qkwjNL._AC_SL1500_.jpg",
    nome: "Vohz Connect",
    descricao: "1200mAh e som premium com Bag de veludo - VOHZ®",
    alt: "Fone de ouvido bluetooth Vohz Connect",
    linkDeCompra: "https://amzn.to/4519Qrt",
    categoria: "Eletrônico",
  },
  {
    id: uuidv4(),
    urlImg: "https://m.media-amazon.com/images/I/510sTPpazeL._AC_SL1200_.jpg",
    nome: "TWS 21 UTBRX",
    descricao:
      "Cancelamento de Ruidos, Compativel com Iphone e Android, Visor Led/Energia para 25 horas, Comandos Touch...",
    alt: "Fone de Ouvido Bluetooth 5.3 sem Fio, TWS 21 UTBRX",
    linkDeCompra: "https://amzn.to/44V6rua",
    categoria: "Eletrônico",
  },
  {
    id: uuidv4(),
    urlImg: "https://m.media-amazon.com/images/I/51RUDt03+XL._AC_SL1000_.jpg",
    nome: "JBL, Headset Gamer, Quantum 100",
    descricao:
      "VOCÊ NO CENTRO DO JOGO. De pequenos passos até a explosão mais alta.",
    alt: "JBL, Headset Gamer, Quantum 100",
    linkDeCompra: "https://amzn.to/4bP7gXO",
    categoria: "Eletrônico",
  },
  {
    id: uuidv4(),
    urlImg: "https://m.media-amazon.com/images/I/51zLcSJWCKL._AC_SL1200_.jpg",
    nome: "Suporte para Notebook e Tablet em Alumínio Resistente Apoio Mesa em Metal Articulado Dobrável Ajustável",
    descricao:
      "Suporte para Notebook e Tablet em Alumínio Resistente Apoio Mesa em Metal Articulado Dobrável Ajustável",
    alt: "Suporte para Notebook e Tablet em Alumínio Resistente Apoio Mesa em Metal Articulado Dobrável Ajustável",
    linkDeCompra: "https://amzn.to/3KN057b",
    categoria: "Eletrônico",
  },
  {
    id: uuidv4(),
    urlImg: "https://m.media-amazon.com/images/I/81ZvbEt1aAL._AC_SL1500_.jpg",
    nome: "Kindle 11ª Geração (modelo 2022) – Mais leve, com resolução de 300 ppi e o dobro de armazenamento - Cor Preta ",
    descricao:
      "Kindle 11ª Geração (modelo 2022) – Mais leve, com resolução de 300 ppi e o dobro de armazenamento - Cor Preta ",
    alt: "Kindle 11ª Geração (modelo 2022) – Mais leve, com resolução de 300 ppi e o dobro de armazenamento - Cor Preta ",
    linkDeCompra: "https://amzn.to/4ar5WJt",
    categoria: "Eletrônico",
  },
  {
    id: uuidv4(),
    urlImg: "https://m.media-amazon.com/images/I/81r5VTxaBiL._SL1500_.jpg",
    nome: "Do mil ao milhão",
    descricao: "Sem cortar o cafézinho",
    alt: "Livro",
    linkDeCompra: "https://amzn.to/3yrmO5E",
    categoria: "Livro",
  },
  {
    id: uuidv4(),
    urlImg: "https://m.media-amazon.com/images/I/81ehvI03NYS._SL1500_.jpg",
    nome: "A psicologia financeira",
    descricao: "lições atemporais sobre fortuna, ganância e felicidade",
    alt: "A psicologia financeira:",
    linkDeCompra: "https://amzn.to/4aIKKPC",
    categoria: "Livro",
  },
  {
    id: uuidv4(),
    urlImg: "https://m.media-amazon.com/images/I/81ALgAW3gHL._SL1500_.jpg",
    nome: "Pai Rico, pai Pobre",
    descricao: "Edição de 20 Anos Atualizada e Ampliada",
    alt: "Pai Rico, pai Pobre",
    linkDeCompra: "https://amzn.to/4bROSxp",
    categoria: "Livro",
  },
  {
    id: uuidv4(),
    urlImg: "https://m.media-amazon.com/images/I/514bcom3x-L._AC_SL1000_.jpg",
    nome: "Vonder Banqueta Plástica Dobrável Branca Altura 220 Mm",
    descricao: "Vonder Banqueta Plástica Dobrável Branca Altura 220 Mm",
    alt: "Vonder Banqueta Plástica Dobrável Branca Altura 220 Mm",
    linkDeCompra: "https://amzn.to/4ckhsbi",
    categoria: "Casa",
  },
  {
    id: uuidv4(),
    urlImg: "https://m.media-amazon.com/images/I/71b3InIEJyL._AC_SL1200_.jpg",
    nome: "Escrivaninha Trevalla Kuadra 150cm Preto Onix",
    descricao: "Escrivaninha Trevalla Kuadra 150cm Preto Onix",
    alt: "Escrivaninha Trevalla Kuadra 150cm Preto Onix",
    linkDeCompra: "https://amzn.to/3xd1RLK",
    categoria: "Casa",
  },
  {
    id: uuidv4(),
    urlImg: "https://m.media-amazon.com/images/I/41sOAAI6e9L._AC_SL1200_.jpg",
    nome: "cadeira de ergonomica escritorio",
    descricao: "cadeira de ergonomica escritorio",
    alt: "cadeira de ergonomica escritorio",
    linkDeCompra: "https://amzn.to/45AQZEa",
    categoria: "Casa",
  },
  {
    id: uuidv4(),
    urlImg: "https://m.media-amazon.com/images/I/61VpeQ3B-JL._AC_SL1000_.jpg",
    nome: "Cadeira de Escritório Secretária Base Cromada com Rodinha",
    descricao: "Cadeira de Escritório Secretária Base Cromada com Rodinha",
    alt: "Cadeira de Escritório Secretária Base Cromada com Rodinha",
    linkDeCompra: "https://amzn.to/45ASySy",
    categoria: "Casa",
  },
  {
    id: uuidv4(),
    urlImg: "https://m.media-amazon.com/images/I/415FZBJSRQL._AC_SL1000_.jpg",
    nome: "Cadeira de Refeição Portátil Smart Cosco - Cinza",
    descricao: "Cadeira de Refeição Portátil Smart Cosco - Cinza",
    alt: "Cadeira de Refeição Portátil Smart Cosco - Cinza",
    linkDeCompra: "https://amzn.to/3KSxQEa",
    categoria: "Casa",
  },
  {
    id: uuidv4(),
    urlImg: "https://m.media-amazon.com/images/I/61VHqEuRgwL._AC_SL1000_.jpg",
    nome: "Cosco Kids, Berço Portátil Happy, 0 a 15kg , Cinza",
    descricao: "Cosco Kids, Berço Portátil Happy, 0 a 15kg , Cinza",
    alt: "Cosco Kids, Berço Portátil Happy, 0 a 15kg , Cinza",
    linkDeCompra: "https://amzn.to/3VtZ8W5",
    categoria: "Casa",
  },
  {
    id: uuidv4(),
    urlImg: "https://m.media-amazon.com/images/I/61e4dMDdxZL._AC_SL1200_.jpg",
    nome: "Corda de Pular em PVC Vollo Vp1075",
    descricao: "Corda de Pular em PVC Vollo Vp1075",
    alt: "Corda de Pular em PVC Vollo Vp1075",
    linkDeCompra: "https://amzn.to/3VP2R1W",
    categoria: "Esporte",
  },
  {
    id: uuidv4(),
    urlImg: "https://m.media-amazon.com/images/I/41CYGAvvnyL._AC_SL1000_.jpg",
    nome: "MINI GALÃO 1875 mL",
    descricao: "MINI GALÃO 1875 mL",
    alt: "MINI GALÃO 1875 mL",
    linkDeCompra: "https://amzn.to/3XqFYmI",
    categoria: "Esporte",
  },
  {
    id: uuidv4(),
    urlImg: "https://m.media-amazon.com/images/I/41fHfQbB81L._AC_SL1000_.jpg",
    nome: "Mibee Compressor de ar portátil com inflador de pneu mini com bateria recarregável de 4000 mAh",
    descricao:
      "Mibee Compressor de ar portátil com inflador de pneu mini com bateria recarregável de 4000 mAh",
    alt: "Mibee Compressor de ar portátil com inflador de pneu mini com bateria recarregável de 4000 mAh",
    linkDeCompra: "https://amzn.to/4b8Trmj",
    categoria: "Esporte",
  },
  {
    id: uuidv4(),
    urlImg: "https://m.media-amazon.com/images/I/51baqU9RjNL._AC_SL1500_.jpg",
    nome: "Speedo Flat Cap , Unissex",
    descricao: "Speedo Flat Cap , Unissex",
    alt: "Speedo Flat Cap , Unissex",
    linkDeCompra: "https://amzn.to/3XuIw32",
    categoria: "Esporte",
  },
  {
    id: uuidv4(),
    urlImg: "https://m.media-amazon.com/images/I/61mFeXRGzML._AC_SL1000_.jpg",
    nome: "YoPRO Bebida Láctea UHT Chocolate 15g de proteínas 250ml - 12 unidades",
    descricao:
      "YoPRO Bebida Láctea UHT Chocolate 15g de proteínas 250ml - 12 unidades",
    alt: "YoPRO Bebida Láctea UHT Chocolate 15g de proteínas 250ml - 12 unidades",
    linkDeCompra: "https://amzn.to/3VP5uAK",
    categoria: "Alimentos",
  },
  {
    id: uuidv4(),
    urlImg: "https://m.media-amazon.com/images/I/61qaI1Z3FML._AC_SL1500_.jpg",
    nome: "Ketchup Heinz Tradicional 1,033KG",
    descricao: "Ketchup Heinz Tradicional 1,033KG",
    alt: "Ketchup Heinz Tradicional 1,033KG",
    linkDeCompra: "https://amzn.to/3VS0n2V",
    categoria: "Alimentos",
  },
  {
    id: uuidv4(),
    urlImg: "https://m.media-amazon.com/images/I/81j00XpMTHS._AC_SL1500_.jpg",
    nome: "Ninho - Leite em Pó, Integral, 380g",
    descricao: "Ninho - Leite em Pó, Integral, 380g",
    alt: "Ninho - Leite em Pó, Integral, 380g",
    linkDeCompra: "https://amzn.to/3XBfa38",
    categoria: "Alimentos",
  },
  {
    id: uuidv4(),
    urlImg: "https://m.media-amazon.com/images/I/51-gMK+tFUL._AC_SL1000_.jpg",
    nome: "Baggio Café Café Torrado E Moído Aroma De Chocolate Trufado 250G",
    descricao:
      "Baggio Café Café Torrado E Moído Aroma De Chocolate Trufado 250G",
    alt: "Baggio Café Café Torrado E Moído Aroma De Chocolate Trufado 250G",
    linkDeCompra: "https://amzn.to/3RCJTJA",
    categoria: "Alimentos",
  },
  {
    id: uuidv4(),
    urlImg: "https://m.media-amazon.com/images/I/81k-iuEeE9L._AC_SL1500_.jpg",
    nome: "ORFEU Café Em Grãos Clássico Orfeu 250G",
    descricao: "ORFEU Café Em Grãos Clássico Orfeu 250G",
    alt: "ORFEU Café Em Grãos Clássico Orfeu 250G",
    linkDeCompra: "https://amzn.to/3Vx2EiB",
    categoria: "Alimentos",
  },
  {
    id: uuidv4(),
    urlImg: "https://m.media-amazon.com/images/I/51Xl8x-Xr4L._AC_SL1000_.jpg",
    nome: "Baggio Café Café Torrado E Moído Aroma De Caramelo 250G",
    descricao: "Baggio Café Café Torrado E Moído Aroma De Caramelo 250G",
    alt: "Baggio Café Café Torrado E Moído Aroma De Caramelo 250G",
    linkDeCompra: "https://amzn.to/3XA4emC",
    categoria: "Alimentos",
  },
  {
    id: uuidv4(),
    urlImg: "https://m.media-amazon.com/images/I/71jm1wFJNbL._AC_SL1500_.jpg",
    nome: "Baggio Café Cápsulas De Café Aroma Chocolate Trufado Compatível Com Nespresso Contém 10 Cápsulas",
    descricao:
      "Baggio Café Cápsulas De Café Aroma Chocolate Trufado Compatível Com Nespresso Contém 10 Cápsulas",
    alt: "Baggio Café Cápsulas De Café Aroma Chocolate Trufado Compatível Com Nespresso Contém 10 Cápsulas",
    linkDeCompra: "https://amzn.to/3XBfFdw",
    categoria: "Alimentos",
  },
  {
    id: uuidv4(),
    urlImg: "https://m.media-amazon.com/images/I/51ahkrmCA+L._AC_SL1000_.jpg",
    nome: "OMO Lavagem Perfeita - Sabão Líquido 5L",
    descricao: "OMO Lavagem Perfeita - Sabão Líquido 5L",
    alt: "OMO Lavagem Perfeita - Sabão Líquido 5L",
    linkDeCompra: "https://amzn.to/3Vy7KLw",
    categoria: "Limpeza",
  },
  {
    id: uuidv4(),
    urlImg: "https://m.media-amazon.com/images/I/412ST6Dk-ZL._AC_SL1000_.jpg",
    nome: "Cif Cremoso Limpeza Milagrosa Remove 100% Da Sujeira 450 Ml",
    descricao: "Cif Cremoso Limpeza Milagrosa Remove 100% Da Sujeira 450 Ml",
    alt: "Cif Cremoso Limpeza Milagrosa Remove 100% Da Sujeira 450 Ml",
    linkDeCompra: "https://amzn.to/3xsmraQ",
    categoria: "Limpeza",
  },
  {
    id: uuidv4(),
    urlImg: "https://m.media-amazon.com/images/I/61FA1mV+kTL._AC_SL1500_.jpg",
    nome: "Dove Sabonete Em Barra Branco 90 Gr 6 Unidades",
    descricao: "Dove Sabonete Em Barra Branco 90 Gr 6 Unidades",
    alt: "Dove Sabonete Em Barra Branco 90 Gr 6 Unidades",
    linkDeCompra: "https://amzn.to/3xv0zM1",
    categoria: "Limpeza",
  },
  {
    id: uuidv4(),
    urlImg: "https://m.media-amazon.com/images/I/61yYqIUxKzL._AC_SL1500_.jpg",
    nome: "Downy Brisa de Verão - Amaciante Concentrado, 3L",
    descricao: "Downy Brisa de Verão - Amaciante Concentrado, 3L",
    alt: "Downy Brisa de Verão - Amaciante Concentrado, 3L",
    linkDeCompra: "https://amzn.to/3VRqx5G",
    categoria: "Limpeza",
  },
];
